item {
    name: "placa carro",
    id: 1,
    display_name: "placa carro"
}
item {
    name: "placa carro mercosul",
    id: 2,
    display_name: "placa carro mercosul"
}
item {
    name: "placa moto",
    id: 3,
    display_name: "placa moto"
}
item {
    name: "placa moto mercosul",
    id: 4,
    display_name: "placa moto mercosul"
}
